// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: 'http://127.0.0.1:9000/api' | (string & {})
}

export type ModelsBaseResponse = {
  code?: number
  data?: unknown
  message?: string
}

export type ModelsFileRequest = {
  file?: unknown
}

export type PostApiV1FileData = {
  /**
   * 文件上传
   */
  body: ModelsFileRequest
  path?: never
  query?: never
  url: '/api/v1/file'
}

export type PostApiV1FileResponses = {
  /**
   * desc
   */
  200: ModelsBaseResponse
}

export type PostApiV1FileResponse =
  PostApiV1FileResponses[keyof PostApiV1FileResponses]
